title: João Víctor Vieira Carneiro
url: "https://joaovvcarneiro.github.io"
#baseurl: "https://joaovvcarneiro.github.io/"
baseurl: "https://joaovvcarneiro.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
#ins_logo: "./bits-logo.png"
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

nav:
 - name: "Home"
   link: "/"
 - name: "Lattes"
   link: "http://lattes.cnpq.br/6985257758397140"
#blog desativado temporariamente 
# - name: "Blog"
#   link: "/blog/"
