title: João Víctor Vieira Carneiro
url: "https://joaovvcarneiro.github.io"
baseurl: "/"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

paginate: 5
paginate_path: "/blog/page:num/"

nav:
 - name: "Home"
   link: "/"
 - name: "Lattes"
   link: "http://lattes.cnpq.br/6985257758397140"
 - name: "Blog"
   link: "/blog/"
